redisdb:
  addr: "localhost:6379"
  password: ""
  db: 0
  poolsize: 10

packetfilter:
  srcport:
    - 1080
  dstport:
    - 1080

etcd:
  endpoints:
    - "localhost:2379"
    - "localhost:22379"
    - "localhost:32379"
  dial-timeout: 5
  
grpc:
  port: 50002