redisdb:
  addr: "192.168.176.128:6379"
  password: ""
  db: 0
  poolsize: 10

packetfilter:
  srcport:
    - 8000
  dstport:
    - 8000

etcd:
  endpoints:
    - "172.17.0.3:2379"
    - "172.17.0.4:2379"
    - "172.17.0.5:2379"
  dial-timeout: 5
  
grpc:
  port: 50003
  mapid: 13
  credentialpath: "../service/strategy/x509/"

rest:
  addr: "localhost:7000"
  production: true