redisdb:
  addr: "192.168.176.128:6379"
  password: ""
  db: 0
  poolsize: 10

packetfilter:
  srcport:
    - 8000
  dstport:
    - 8000

etcd:
  endpoints:
    - "172.17.0.5:2379"
    - "172.17.0.6:2379"
    - "172.17.0.7:2379"
  dial-timeout: 5
  
grpc:
  port: 50003
  mapid: 39

rest:
  addr: "localhost:7000"
  production: true